export const ValidationErrorMessage = {
    UsernameRequired: 'Username is required',
    UsernameWrongFormat: 'Username is not correct. Required minimum 3 characters and maximum 25 characters',
    UsernameAlreadyExist: 'This username is currently used',
    UsernameIncorrect: 'Username contains illegal characters',
    LoginDoesntExist: 'We can not find any user with this login',
    LoginIncorrect: 'Login contains illegal characters',
    EmailRequired: 'Email is required',
    EmailWrongFormat: 'Enter valid email address',
    EmailAlreadyExist: 'This email address is currently used',
    PasswordRequired: 'Password is required',
    PasswordWrongFormat: 'Password is not correct. Required minimum 8 characters',
    PasswordIncorrect: 'Password contains illegal characters',
    PasswordsAreNotTheSame: 'Passwords must be the same',
    PasswordWrong: 'Password is wrong',
    AccountRequired: 'Account type is required',
    CategoryTitleRequired: 'Category title is required',
    CategoryTitleWrongFormat: 'Category title contains illegal characters',
    CategoryTitleTooShort: 'Category title is too short. Required minimum 3 characters',
    CategoryDescriptionWrongFormat: 'Category description contains illegal characters',
}